pipeline {
    agent any
    tools {
        jdk 'jdk21' // This name must match the JDK installation name used in Jenkins Global Tool Configuration
    }
    environment {
        DOCKER_PASSWORD = credentials("docker_password")
    }

    stages {
        stage('Build & Test') {
            steps {
                sh './gradlew clean build'
            }
        }
        stage('Tag image') {
            steps {
                script {
                    def GIT_TAG = sh([script: 'git fetch --tag && git tag', returnStdout: true]).trim()
                    def MAJOR_VERSION = sh([script: 'git tag | cut -d . -f 1', returnStdout: true]).trim()
                    def MINOR_VERSION = sh([script: 'git tag | cut -d . -f 2', returnStdout: true]).trim()
                    def PATCH_VERSION = sh([script: 'git tag | cut -d . -f 3', returnStdout: true]).trim()
                    
                    echo "Git Tags: ${GIT_TAG}"
                    echo "Version: ${MAJOR_VERSION}.${MINOR_VERSION}.${PATCH_VERSION}"
                    
                    def newMinorVersion = MINOR_VERSION.toInteger() + 1
                sh "docker build -t makebuild/hello-img:${MAJOR_VERSION}.\$((${MINOR_VERSION} + 1)).${PATCH_VERSION} ."
                }
            }
        }
    }
